#!/usr/bin/env bash
# scripts/preflight.sh — local reproduction of the CI gates before `git push`.
# Generated by ~/claude-config/scripts/gen-preflight.py from the workflows below;
# every command is the one CI runs. A step this file does not cover is a step
# that can only fail remotely — when a workflow step is added, regenerate or
# add it here in the same commit. ~/.claude/hooks/pre-push-preflight.sh runs
# `--quick` before every push and blocks on failure.
#
# usage: scripts/preflight.sh [--quick]   (--quick skips the test / bench suites)
set -euo pipefail
cd "$(dirname "$0")/.."

quick=0
[[ "${1:-}" == "--quick" ]] && quick=1

step() { printf '\n\033[1;34m== %s\033[0m\n' "$*"; }
# `cargo clippy` reuses fresh `cargo check` artifacts and then lints nothing;
# touching the crate roots invalidates only this repo's fingerprints.
relint() { git ls-files | grep -E '(^|/)src/(lib|main)\.rs$' | xargs -r touch; }
need() { command -v "$1" >/dev/null 2>&1 || { echo "missing tool: $1 ($2)" >&2; exit 1; }; }
has_toolchain() { rustup toolchain list | grep -q "^$1"; }

# Steps CI runs that this file cannot reproduce locally (they can only fail remotely):
#   - ci-unified.yml:clippy:Create dependency stubs (sibling path deps) (no cargo / grep)
#   - ci-unified.yml:test:Create dependency stubs (sibling path deps) (no cargo / grep)
#   - ci-unified.yml:doctest:Create dependency stubs (sibling path deps) (no cargo / grep)
#   - ci-unified.yml:build:Create dependency stubs (sibling path deps) (no cargo / grep)

need actionlint "brew install actionlint"

step "ci.yml / test: Build (no default features)"
( export CARGO_TERM_COLOR="always"; cargo build --lib --no-default-features )

step "ci.yml / test: Build (async)"
( export CARGO_TERM_COLOR="always"; cargo build --lib --features "async" )

step "ci.yml / test: Build (simd)"
( export CARGO_TERM_COLOR="always"; cargo build --lib --features "simd" )

step "ci.yml / test: Build (cloud)"
( export CARGO_TERM_COLOR="always"; cargo build --lib --features "cloud" )

step "ci.yml / test: Check (all features、bridge 含む)"
( export CARGO_TERM_COLOR="always"; cargo check --lib --all-features )

step "ci.yml / clippy: Clippy (core features)"
relint
( export CARGO_TERM_COLOR="always"; cargo clippy --features std -- -W clippy::all )

step "ci.yml / clippy: Clippy (cloud)"
relint
( export CARGO_TERM_COLOR="always"; cargo clippy --features cloud -- -W clippy::all )

step "ci.yml / fmt: Check formatting"
( export CARGO_TERM_COLOR="always"; cargo fmt -- --check )

step "ci.yml / actionlint: actionlint"
actionlint .github/workflows/*.yml

step "ci-unified.yml / fmt: run"
( export CARGO_TERM_COLOR="always" CARGO_INCREMENTAL="0" RUST_BACKTRACE="short"; cargo fmt --all -- --check )

step "ci-unified.yml / clippy: run"
relint
( export CARGO_TERM_COLOR="always" CARGO_INCREMENTAL="0" RUST_BACKTRACE="short"; cargo clippy --workspace --all-targets --all-features -- -D warnings )

step "ci-unified.yml / build: run"
( export CARGO_TERM_COLOR="always" CARGO_INCREMENTAL="0" RUST_BACKTRACE="short"; cargo build --workspace --all-features --release )

if [[ $quick -eq 1 ]]; then
  echo; echo "preflight --quick OK (test / bench suites skipped)"; exit 0
fi

step "ci.yml / test: Test (default = std)"
( export CARGO_TERM_COLOR="always"; cargo test --features std )

step "ci.yml / test: Doc tests"
( export CARGO_TERM_COLOR="always"; cargo test --features std --doc )

step "ci-unified.yml / test: run"
( export CARGO_TERM_COLOR="always" CARGO_INCREMENTAL="0" RUST_BACKTRACE="short"; cargo nextest run --workspace --all-features )

step "ci-unified.yml / doctest: run"
( export CARGO_TERM_COLOR="always" CARGO_INCREMENTAL="0" RUST_BACKTRACE="short"; cargo test --doc --workspace --all-features )

echo; echo "preflight OK"
